### ISSUE TITLE
Folders and Icons in tree view

### ISSUE THREAD

**Issue by zam6ak** [jsreport/jsreport-studio#11]
Any chance of adding
1) folders in templates tree view
2) icons indicating template recipe

Explanation:

1) 
Often I have same "logical" report but it has 3-4 different templates with different layouts and recipes 
Having a folder where I can group templates per report would make it easier to organize things...
Having a flat list makes it difficult to navigate when there is a lot of reports...

2)
Currently, the icon under templates tree is static (looks like a area chart).
This forces me to put type of the template in the name, For example:
report-one-html
report-one-pdf
report-one-excel
and so on....I still may have to do this to keep the names unique but it would help navigation, IMHO.

**Comment by pofider** [comment]
Please split this into two github issues. Both makes very much sense.

**Comment by zam6ak** [comment]
Done!
