### ISSUE TITLE
Feature: Add icons indicating recipe and engine

### ISSUE THREAD

**Issue by zam6ak** [jsreport/jsreport-studio#13]
As per recommendation from @pofider in issue #11 

Would it be possible to add icons indicating which recipe and templating engine the template is using?
Currently, the icon under templates tree is static (looks like a area chart).
This forces me to put type of the template in the name, For example (hb == handlebars):

```
report-one-hb-html
report-one-hb-pdf
report-one-hb-excel
report-two-hb-html
report-two-hb-pdf
report-two-hb-excel
```

and so on....I still may have to do this to keep the names unique but it would help navigation, IMHO.

Thanks
Z!

**Comment by pofider** [comment]
Sure recipe makes very much sense. Lets replace the icon with a custom icon provided by the recipe...

I'm not sure about the engine. Users usually get familiar with a single recipe and use it everywhere. Lets rather save the space in the entity tree for something else like labels.

**Comment by zam6ak** [comment]
recipe icon only works for me! :)

**Comment by pofider** [comment]
I was looking at this feature now and realized that there are not so many meaning full icons at least in font  awesome we use. This would be likely a discotheque of misleading icons. Perhaps better to solve this just with different colors of the default icon.

**Comment by zam6ak** [comment]
What is missing from FA? html, pdf, excel, text, xml, all have icons....

**Comment by pofider** [comment]
The pdf can be generated using fop, wkhtmltopdf, phantom and electron. Excel can be generated using xlsx and html-to-xlsx. 

Maybe the best to put both ideas together. Lets have a pdf icon for those 4 but with different fg colors.

**Comment by zam6ak** [comment]
Colors, in my opinion, would make it look busy....Perhaps Bootstrap labels or badges (tiny ones), with different color, next to name?

**Comment by pofider** [comment]
label or badge would need to be very tiny to don't take too much space. I'm gonna try something and share a screen.

**Comment by pofider** [comment]
Release 1.2.0 now enables custom icons in entity tree. So far the phantom-pdf and html recipe supports this. 

Additionally the scripts extension has different icon for a global script and assets have different icons for html, js, css and images 

The other recipes will come step by step.
