### ISSUE TITLE
Feature: Add folders in studio

### ISSUE THREAD

**Issue by zam6ak** [jsreport/jsreport-studio#14]
As per recommendation from @pofider in issue #11 

Would it be possible to add ability to organize templates (and other items, scripts, data, etc, etc) in foders?

Often I have same "logical" report but it has 3-4 different templates with different layouts and recipes 
Having a folder where I can group templates per report would make it easier to organize things...
Having a flat list makes it difficult to navigate when there is a lot of reports...

Thanks
Z!

**Comment by pofider** [comment]
Thinking if we will go the folders way or tag/labels way.

The tags/labels give us probably more powerful and flexible solution:
1. User can create a custom tag and label the entities.
2. User can filter the entity tree panels by tags
3. User can filter the entity tree with standard tags like give me entities with particular recipe or with particular script

The downside is that visual user experience with labels is probably not so good as with folders. You get just raw list in which you need to filter.

I'll have to give it some more thoughts, every suggestion is welcome.

**Comment by zam6ak** [comment]
Folders would give you hierarchical organization.
Tags/labels are more "taxonomy" oriented.

And with labels, as you mention, you still have (initially) a long list to contend with.
I imagine as the number of items in thee grows, folders would help with faster loading (expand on AJAX request) instead of loading everything...

But I like labels idea also. 
Can we have both? :)

**Comment by pofider** [comment]
The implementation will have impact on several extensions, so I moved it to the main repo.
https://github.com/jsreport/jsreport/issues/250
