### ISSUE TITLE
Entity set order in the entity tree

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-studio#22]
The extension should be able to specify the position of entities in the entity tree.

This is can be done probably in the 

```js
Studio.addEntitySet({
  name: 'assets',
  faIcon: 'fa-file',
  visibleName: 'asset',
  onNew: () => Studio.openModal(NewAssetModal),
  referenceAttributes: ['isSharedHelper'],
  entityTreePosition: 200
})
```

I expect it to be in the end: templates, data, scripts, assets, images, xlsxTemplates, schedules, tags, users

The similar should work also for the properties. This is just rough spec, doesn't need to be realized in the same way.

**Comment by bjrmatos** [comment]
this feature has been implemented

also i've sent PRs over extensions repositories to allow the desired default ordering 😄 :

**templates (1000)**, **data (900)**, **scripts (800)**, **assets (700)**, **images (600)**, **xlsxTemplates (500)**, **schedules (400)**, **tags (300)**, **users (200)**
