### ISSUE TITLE
depend on react 0.14.x or 15.x

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport-studio#3]
seems like react@0.14.x has been used to develop jsreport-studio, but you have [one dependency for react@15.x](https://github.com/jsreport/jsreport-studio/blob/master/package.json#L80), in fact this issue break my install in npm@2

<img width="394" alt="captura de pantalla 2016-05-21 a las 11 33 57 a m" src="https://cloud.githubusercontent.com/assets/4262050/15449606/ee02c35c-1f47-11e6-8bc1-3f9a6d1ed835.png">

**Comment by pofider** [comment]
This is fixed now along with #4
