### ISSUE TITLE
Safari/IE tab layout issue

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-studio#30]
The safari seems to wrongly display tabs. It looks like the same problem on internet explorer.
![safari](https://cloud.githubusercontent.com/assets/2041960/24444802/02325976-1468-11e7-959d-87e1cbc63322.png)

These browsers are rarely used to reach jsreport (like 4%). It is not urgent to fix this if it should take long. However a dialog with message `You seems to be using Safari which may have issues with displaying jsreport studio correctly. We recommend to run jsreport studio in the latest Chrome or Firefox.`

**Comment by bjrmatos** [comment]
and seems like it is working in IE 11 too 
![captura de pantalla 2017-04-10 a las 6 25 01 p m](https://cloud.githubusercontent.com/assets/4262050/24886559/1f04cbda-1e1b-11e7-9b5a-64bd2ff0b3ae.png).

i will close the issue, if there is another problem we can reopen or create a new issue 👍

**Comment by pofider** [comment]
Excellent! Thank you. We will ship it along with jsreport@1.7
