### ISSUE TITLE
Validate entities name prior to creation

### ISSUE THREAD

**Issue by fmmich** [jsreport/jsreport-studio#35]
When using the embedded file store, Jsreport Studio allows the user to use characters in ~~asset names~~ entity name that shouldn't be allowed.  Specifically on Windows operating systems, the following characters should not be used: 

- \\ (backslash)
- / (forward slash)
- : (colon)
- \* (asterisk)
- ? (question mark)
- " (double quotes)
- < (less than sign)
- \> (greater than sign)
- | (pipe)

In addition, ~~asset names~~ entity name should not start or end with spaces.  The Windows operating system cannot move, rename, or delete directories containing leading or trailing spaces very easily.

I would agree that the simple answer is "don't do that." I'm logging this because we discovered by accident that ~~assets~~ entities with these characters place files outside of their expected storage location, and this software change would prevent possible problems with your other customers.

Thank you for your consideration.

**Comment by bjrmatos** [comment]
good catch! the validation makes sense so i think we are going to implement this.

thnks for let us know

**Comment by bjrmatos** [comment]
i guess that the validation should be applied to every entity (not only assets)

i have updated the title of the issue to reflect that.

**Comment by pofider** [comment]
We already have validation for `/` and error pop up `Document cannot contain / in the name` in place here
https://github.com/jsreport/jsreport-fs-store/blob/master/lib/persistence.js#L195

We should likely just extend this validation with other mentioned characters there.

I'm thinking if we shouldn't do this generally for all stores somewhere in jsreport-core. This limitation doesn't exist in other stores. Memory, mongo or sql has no problems with it. However having the limitation everywhere would make it more "cross platform" and simplify the export/import and moving the templates through stores.

**Comment by bjrmatos** [comment]
> I'm thinking if we shouldn't do this generally for all stores somewhere in jsreport-core. This limitation doesn't exist in other stores. Memory, mongo or sql has no problems with it. However having the limitation everywhere would make it more "cross platform" and simplify the export/import and moving the templates through stores.

yes, that is what i was thinking (i have not put it in my comments 😁), validation across any store is the way to go. we can use [this module](https://github.com/sindresorhus/valid-filename) (or take its code if we want to support node `0.10.x`) to help us with the task

**Comment by bjrmatos** [comment]
done
