### ISSUE TITLE
found  vulnerabilities

### ISSUE THREAD

**Issue by jagdeep-anetcorp** [jsreport/jsreport-studio#39]
Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   jsreport

  Path            jsreport > jsreport-studio > compression > debug

  More info       https://nodesecurity.io/advisories/534

**Comment by pofider** [comment]
https://github.com/jsreport/jsreport/issues/354#issuecomment-377030562
