### ISSUE TITLE
npm start, npm run build fails in npm@2

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport-studio#4]
seems like you were using npm@3 to develop this package and because of that maybe some things work on your machine but when doing a fresh install with npm@2 problems start to appear.

first thing i noticed was that there is no `less-loader` in dependencies

<img width="1894" alt="captura de pantalla 2016-05-21 a las 11 58 25 a m" src="https://cloud.githubusercontent.com/assets/4262050/15449721/b65dafc6-1f4b-11e6-867a-95eca5c187c3.png">

**Comment by pofider** [comment]
True, I downgraded to npm@2 and fix the missing dependencies. Now it should work. I'm sorry for the troubles.
