### ISSUE TITLE
Cloning assets in Studio doesn't work in 2.6

### ISSUE THREAD

**Issue by msageryd** [jsreport/jsreport-studio#45]
Right click on an asset and selecting `clone` in Studio 2.5, resulted in a cloned asset. Quite handy function.

Doing the same in Studio 2.6 results in a cloned assed shown in the folder tree in Studio, but there is no clone on disk. Refreshing Studio reveals that the asset never existed (i.e it disappears on refresh)

**Comment by bjrmatos** [comment]
hi! i tried to reproduce the issue but no luck..

do you have some other details to reproduce this? does it happen for any asset? does it happen for other entities like cloning a template? 

what i tried was to initialize a new project with `jsreport init`, after that i started the server, created a folder "testing", inside i've created a `demo.css` asset, save, then right click on the demo.css asset, clone, confirm, save and i can see the entity on the filesystem.

<img width="827" alt="Captura de pantalla 2019-09-24 a la(s) 6 10 41 p  m" src="https://user-images.githubusercontent.com/4262050/65556828-a6024b00-def6-11e9-9438-a3c602c070b6.png">

<img width="295" alt="Captura de pantalla 2019-09-24 a la(s) 6 07 22 p  m" src="https://user-images.githubusercontent.com/4262050/65556835-aac6ff00-def6-11e9-8384-438568fb357f.png">

**Comment by msageryd** [comment]
I see now that it works, but I have to explicitly save the cloned asset. I don't think that 2.5 behaved like this. Now when I got the concept, it's no big deal. Please go ahead and close this if you'd like.

1. right click an asset (I tried with .css .svg .png) and select clone
2. Name the clone or use suggested name
3. Cloned asset is created in Studio with an asterisk
4. If you don't click on the clone and hit **save**, the clone disappears

**Comment by bjrmatos** [comment]
hmm i tried the same in 2.5.0 and the behaviour there is the same, i guess there was just some confusion because we expect the clone feature to create entity in dirty state first, and then you save it explicitly in order to have it in the store.
