### ISSUE TITLE
Task generated report return 404 with appPath & mountOnAppPath

### ISSUE THREAD

**Issue by grisson2** [jsreport/jsreport-studio#47]
Jsreport 2.6.1

Apply the seguent config to jsreport.config.js

```  
appPath: '/some/path/jsreport',

mountOnAppPath: true
```

When the user wants to show a task-generated pdf, the node web service give a 404 error because the studio tries to load the generate file using the url

```
http://host:port/reports/[ID]/content
```

instead of 

```
http://host:port/some/path/jsreport/reports/[ID]/content
```

Manually fixing the url in a new browser tab correctly show the expected pdf.

Guess it's just a forgotten path concatenation

**Comment by pofider** [comment]
Thank you for the bug report. @bjrmatos Please take a look at this.

**Comment by bjrmatos** [comment]
@grisson2 thanks for the bug report. we have fixed this in 3 different places, so if you want to try it right now you can install the following deps from git `npm i jsreport/jsreport-studio jsreport/jsreport-reports jsreport/jsreport-scheduling`

**Comment by grisson2** [comment]
Ok, thank you, will try soon.
