### ISSUE TITLE
How to add a new user to JSReport Studio

### ISSUE THREAD

**Issue by 1Map** [jsreport/jsreport-studio#48]
Hi, I am new to JSReport.  I have installed jsreport on my linux server and jsreport studio opens up at 5488 from the browser.  I am then able to login with my admin user.  The question now is:  How can I add additional users?

**Comment by pofider** [comment]
![image](https://user-images.githubusercontent.com/2041960/124597875-458e9480-de64-11eb-9a40-d90db8f7ec50.png)

You can use + button in the entity tree and create a new user entity.
